# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c88ef2033625d52ec264b3a5990541efcf92d7b29f41d09ecaa4909eb2249d3a9cbdd32fc744a3a465e04d6f3694145d42dfeb990d7c00224a4bf0c3ef196f7

test:
  secret_key_base: 0f233f43b89615dcfd7a8935163087bfe1840c108cf033ba929de3e014e516fc5118f7f6d816fe2125f1e8a791a81217e71e60cd7926a55ebfa9b3c6f7192f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
